version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.7.4
    env_file: ./.env
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
